### ISSUE TITLE
FilePicker.qml:175:9: QML Item: Binding loop detected for property "width"

### ISSUE THREAD

**Issue by romaxa** [tmeshkova/qmlmozbrowser#13]
EmbedLiteExt QGraphicsMozView:RecvAsyncMessage:199: mesg:embed:filepicker, data:{"name":"linux-3.8.3.tar.xz","title":"","mode":1,"winid":1}
onRecvAsyncMessage:embed:filepicker, data:[object Object]
qrc:/qml/FilePicker.qml:175:9: QML Item: Binding loop detected for property "width"
FilePicker selected: null accepted: false
nsEmbedFilePicker::GetFile IMPLEMENTED

**Comment by CODeRUS** [comment]
Fixed in https://github.com/tmeshkova/qmlmozbrowser/commit/0cd9f08d9b169845591beacf69fada3ceb83d7d8
