### ISSUE TITLE
Download pause/resume does not work for just added download

### ISSUE THREAD

**Issue by romaxa** [tmeshkova/qmlmozbrowser#14]
./qmlMozEmbedTest -url www.kernel.org
1) Click  on download link and start download
2) open download page
3) Click Pause button

RESULT: download paused, but button still in running state (II) state
EXPECTED: download paused, and button in  resume state (>)

**Comment by CODeRUS** [comment]
DownloadManagerUI sometimes not sending dl-state with new download.state. I hope you can help here.

**Comment by CODeRUS** [comment]
should be fixed by https://github.com/tmeshkova/embedlite-components/commit/76b0961930808804d262cbae8309f56408b1bbd1
confirm please
